pipeline {
    agent any

    stages {
        stage('Build Docker image') {
            steps {
                script {
                    bat 'docker build -t nutricraft_image .'
                }
            }
        }
        stage('Tag image') {
            steps {
                script {
                    bat 'docker tag nutricraft carribo/nutricraft_image'
                }
            }
        }
        stage('Push image') {
            environment {
                DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
            }
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_HUB_USERNAME', passwordVariable: 'DOCKER_HUB_PASSWORD']]) {
                    script {
                        bat 'docker logout'
                        bat "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}"
                        bat 'docker push carribo/nutricraft_image'
                        bat 'echo "Hello"'
                    }
                }
            }
        }
    }
}